 # Default values for the generator
 # this file can be used as a template for a custom configuration
 # or to know about the different variables available for the generator
      platys:
        platform-name: 'streaming-platform'
        platform-stack: 'trivadis/platys-modern-data-platform'
        platform-stack-version: '1.13.0-preview'
        structure: 'flat'

      #zookeeper
      ZOOKEEPER_enable: true
      ZOOKEEPER_volume_map_data: false
      ZOOKEEPER_nodes: 1            # either 1 or 3

      #kafka
      KAFKA_enable: true
      # one of enterprise, community
      KAFKA_edition: 'community'
      KAFKA_volume_map_data: false
      KAFKA_broker_nodes: 3
      KAFKA_delete_topic_enable: true
      KAFKA_auto_create_topics_enable: false

      #kafka schema registry
      KAFKA_SCHEMA_REGISTRY_enable: true
      KAFKA_SCHEMA_REGISTRY_nodes: 1
      KAFKA_SCHEMA_REGISTRY_use_zookeeper_election: false
      KAFKA_SCHEMA_REGISTRY_replication_factor: 1

      #kafka connect
      KAFKA_CONNECT_enable: true
      KAFKA_CONNECT_nodes: 2
      KAFKA_CONNECT_connectors: 'confluentinc/kafka-connect-jdbc:10.0.0,confluentinc/kafka-connect-elasticsearch:11.0.6,jcustenborder/kafka-connect-twitter:0.3.33'

      #misc kafka 'addons'
      KAFKA_KSQLDB_enable: true
      KAFKA_KSQL_edition: 'oss'
      KAFKA_KSQLDB_nodes: 1

      # Kafka Confluent Control Center
      KAFKA_CCC_enable: false

      KAFKA_RESTPROXY_enable: false
      KAFKA_MQTTPROXY_enable: false

      KAFKACAT_enable: true

      KAFKA_SCHEMA_REGISTRY_UI_enable: true
      KAFKA_SCHEMA_REGISTRY_UI_use_public_ip: false
      KAFKA_CONNECT_UI_enable: true
      KAFKA_CONNECT_UI_use_public_ip: false

      KAFKA_CMAK_enable: true
      KAFKA_KAFDROP_enable: false
      KAFKA_KADMIN_enable: false
      KAFKA_AKHQ_enable: true
      KAFKA_BURROW_enable: false

      #hadoop
      HADOOP_enable: false
      HADOOP_datanodes: 1

      #spark
      SPARK_enable: false
      SPARK_workers: 2
      SPARK_jars_packages: "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.5,org.postgresql:postgresql:42.2.12"

      # misc spark 'addons'
      SPARK_HISTORY_enable: false
      SPARK_THRIFT_enable: false
      
      # Apache Livy
      LIVY_enable: false

      # Apache Hive
      HIVE_enable: false

      # Apache Atlas
      ATLAS_enable: false
      ATLAS_provision_atlas_sample_data: false
      ATLAS_provision_amundsen_sample_data: false
      ATLAS_install_hive_hook: false

      #amundsen
      AMUNDSEN_enable: false
      # one of 'amundsen-metastore' or 'atlas-metastore'
      AMUNDSEN_edition: 'amundsen-metastore'

      #hue
      HUE_enable: false

      #streamsets and stremsets edge
      STREAMSETS_enable: true
      STREAMSETS_volume_map_data: false
      STREAMSETS_TRANSFORMER_enable: false
      STREAMSETS_TRANSFORMER_volume_map_data: false
      STREAMSETS_EDGE_enable: true
      STREAMSETS_EDGE_volume_map_data: false

      #nifi
      NIFI_enable: true

      #nodered
      NODERED_enable: false
      NODERED_volume_map_data: false

      #streamsheets
      STREAMSHEETS_enable: false

      #zeppelin
      ZEPPELIN_enable: true
      ZEPPELIN_volume_map_data: false

      #jupyter
      JUPYTER_enable: false
      # one of 'minimal', 'r', 'scipy', 'tensorflow', 'datascience', 'all_spark'
      JUPYTER_edition: 'minimal'
      JUPYTER_volume_map_data: false

      # Visualization
      GRAFANA_enable: false
      KIBANA_enable: false #needs to have elasticsearch enabled to work
      
      # NoSQL
      REDIS_enable: false
      CASSANDRA_enable: false
      MONGO_enable: false
      SOLR_enable: false
      ELASTICSEARCH_enable: false

      NEO4J_enable: false
      NEO4J_volume_map_data: false
      NEO4J_volume_map_logs: false
      
      # Influx DB 1.x
      INFLUXDB_enable: false
      INFLUXDB_volume_map_data: false
      INFLUXDB_TELEGRAF_enable: false
      INFLUXDB_CHRONOGRAF_enable: false
      INFLUXDB_CHRONOGRAF_volume_map_data: false
      INFLUXDB_KAPACITOR_enable: false
      INFLUXDB_KAPACITOR_volume_map_data: false

      # Influx DB 2.x
      INFLUXDB2_enable: false
      INFLUXDB2_volume_map_data: false

      # NoSQL - Prometeus
      PROMETHEUS_enable: false
      PROMETHEUS_volume_map_data: false
      PROMETHEUS_PUSHGATEWAY_enable: false
      
      # NoSQL - Tile38
      TILE38_enable: false

      # RDBMS
      MYSQL_enable: false
      SQLSERVER_enable: false

      POSTGRESQL_enable: true
      POSTGRESQL_volume_map_data: false
      TIMESCALEDB_enable: false
      TIMESCALEDB_volume_map_data: false

      ADMINER_enable: true

      # Event Store
      AXON_enable: false

      # MQTT
      MQTT_enable: true
      MOSQUITTO_enable: true #needs MQTT_ENABLE = true
      MOSQUITTO_nodes: 1
      MOSQUITTO_volume_map_data: false
      HIVEMQ3_enable: false #needs MQTT_ENABLE = true
      HIVEMQ4_enable: false #needs MQTT_ENABLE = true
      MQTT_UI_enable: true #needs MQTT_ENABLE = true
      ACTIVEMQ_enable: false

      # MinIO Object Storage
      MINIO_enable: true
      MINIO_volume_map_data: false

      AWSCLI_enable: false

      # FTP
      FTP_enable: false

      # Container Mgmt
      PORTAINER_enable: false
      CADVISOR_enable: false
      WETTY_enable: true

      MARKDOWN_VIEWER_enable: true
      
      # Python image
      PYTHON_enable: false
      PYTHON_script_folder: ''
      PYTHON_script: ''


