services:

  kafka-producer-app:
    build:
      context: .
      dockerfile: scripts/docker/kafka-producer-app/Dockerfile
    container_name: kafka-producer-app
    hostname: kafka-producer-app
    depends_on:
     - kafka-1
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka-1:19092
    restart: always
