apiVersion: "kafka.jikkou.io/v1beta2"
kind: "KafkaTopicList"
metadata: {}
items:
  - metadata:
      name: '{{ labels.topic.prefix | default('') }}bluesky.raw'
    spec:
      partitions: 3
      replicas: {{ values.topicConfigs.replicas }}
  - metadata:
      name: '{{ labels.topic.prefix | default('') }}app.bsky.actor.profile'
    spec:
      partitions: 3
      replicas: {{ values.topicConfigs.replicas }}
  - metadata:
      name: '{{ labels.topic.prefix | default('') }}app.bsky.feed.like'
    spec:
      partitions: 3
      replicas: {{ values.topicConfigs.replicas }}
  - metadata:
      name: '{{ labels.topic.prefix | default('') }}app.bsky.feed.post'
    spec:
      partitions: 3
      replicas: {{ values.topicConfigs.replicas }}
  - metadata:
      name: '{{ labels.topic.prefix | default('') }}app.bsky.feed.repost'
    spec:
      partitions: 3
      replicas: {{ values.topicConfigs.replicas }}
  - metadata:
      name: '{{ labels.topic.prefix | default('') }}app.bsky.graph.follow'
    spec:
      partitions: 3
      replicas: {{ values.topicConfigs.replicas }}
